# 例5-2步骤
首先导入数据，进行初始化

In [1]:
import numpy as np
stage=3
k=6
q=range(0,501,100)
g=np.array([[0.,0.,0.],[30.,50.,40.],[70.,100.,60.],[90.,110.,110.],[120.,110.,120.],[130.,110.,120.]])
f=np.zeros((k,stage))
x=np.zeros((k,stage))
print("g:\n",g)
print("f:\n",f)

g:
 [[  0.   0.   0.]
 [ 30.  50.  40.]
 [ 70. 100.  60.]
 [ 90. 110. 110.]
 [120. 110. 120.]
 [130. 110. 120.]]
f:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


计算阶段三  
直接填入相应的数据

In [2]:
f[:,2]=g[:,2]
x[:,2]=range(0,6)

计算阶段二  
先计算三角矩阵，然后求每行的最大值  
![ ](./image/动态规划第二阶段.png)

In [3]:
triangularMatrix=np.tile(g[:,1],(k,1))
for i in range(0,k):
    triangularMatrix[:,i]+=np.roll(f[:,2],i)
triangularMatrix=np.tril(triangularMatrix,0)
print('triangularMatrix:\n',triangularMatrix)
f[:,1]=triangularMatrix.max(axis=1)
print('f:\n',f[:,1])
x[:,1]=np.argmax(triangularMatrix,axis=1)

triangularMatrix:
 [[  0.   0.   0.   0.   0.   0.]
 [ 40.  50.   0.   0.   0.   0.]
 [ 60.  90. 100.   0.   0.   0.]
 [110. 110. 140. 110.   0.   0.]
 [120. 160. 160. 150. 110.   0.]
 [120. 170. 210. 170. 150. 110.]]
f:
 [  0.  50. 100. 140. 160. 210.]


计算阶段一 同理

In [4]:
triangularMatrix=np.tile(g[:,0],(k,1))
for i in range(0,k):
    triangularMatrix[:,i]+=np.roll(f[:,1],i)
triangularMatrix=np.tril(triangularMatrix,0)
print('triangularMatrix:\n',triangularMatrix)
f[:,0]=triangularMatrix.max(axis=1)
print('f:\n',f[:,0])
x[:,0]=np.argmax(triangularMatrix,axis=1)

triangularMatrix:
 [[  0.   0.   0.   0.   0.   0.]
 [ 50.  30.   0.   0.   0.   0.]
 [100.  80.  70.   0.   0.   0.]
 [140. 130. 120.  90.   0.   0.]
 [160. 170. 170. 140. 120.   0.]
 [210. 190. 210. 190. 170. 130.]]
f:
 [  0.  50. 100. 140. 170. 210.]
